### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by Zane-XY** [tidyparse/tidyparse#1]
run `./gradlew build` gets below errors:

```
> Configure project :tidyparse-web-frontend
w: 'kotlin-js' Gradle plugin is deprecated and will be removed in the future. 
Please use 'kotlin("multiplatform")' plugin with a 'js()' target instead. See the migration guide: https://kotl.in/t6m3vu

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':tidyparse-core:compileCommonMainKotlinMetadata'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':tidyparse-core:commonMainResolvableDependenciesMetadata'.
      > Could not resolve ai.hypergraph:kaliningraph.
        Required by:
            project :tidyparse-core
         > No matching configuration of project :galoisenne was found. The consumer was configured to find a library for use during 'kotlin-metadata', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' but:
             - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

```
I'm interested how can you get the build work.

**Comment by breandan** [comment]
You need to initiate the submodule: `git submodule update --init --recursive`

edit: There is also a [web demo](http://tidyparse.github.io) with some minimal functionality if you feel like playing with the tool, it should work on Firefox and Safari.

**Comment by Zane-XY** [comment]
Hi @breandan , thanks for the quick response. 
Is this issue resolved? https://youtrack.jetbrains.com/issue/IJSDK-1616/Unable-to-resolve-Gradle-plugin-dependency-provided-by-the-gradle-intellij-plugin-in-a-multimodule-project
I came here to checkout how you get the build work.

I'm also working on a similar structured project, where I have shared subproject that compiles to kotlin-multiplatform, and the intellij-plugin suproject needs target to kotlin-jvm but depends on the shared module. 
If I use kotlin-jvm plugin to compile the plugin, it can't find the shared module. If I switch to the kotlin-mutiplatform, then, it can't find the intellij sdk dependency configured by the intellij plugin. 
So i'm wondering how you achieved it, is the build problem now completely solved?

**Comment by breandan** [comment]
Ah, I see now where you're coming from. I have no clue if IJSDK-1616 was ever fixed as I ended up using a different  project structure altogether. It is a mystery to me how Gradle works at all, but the current build seems to be stable. I compile the IntelliJ Platform plugin using `./gradlew buildPlugin`/`./gradlew runIde` and the web frontend using `./gradlew :tidyparse-web-frontend:browserDevelopmentRun`/`./gradlew browserProductionWebpack` which suits my purposes. I am reluctant to change anything as Gradle is completely unpredictable. I suspect this is a widely-known issue as they are moving towards a new [declarative build system](https://blog.gradle.org/declarative-gradle).

edit: I was just thinking about this the other day, as this project is fairly unique. I suspect it is one of the only, if not the only project that uses (1) Kotlin Multiplatform (2) IntelliJ Platform (3) Gradle multimodule and (4) Git submodules in a single build. To my astonishment, it does work, but I deeply regret the pain it took to set up.

**Comment by Zane-XY** [comment]
I absolutely feel the same way. I compared my build script line by line with yours, and found in my shared library, I didn't have `withJava()`:
```
    jvm {
        compilations.all {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
        withJava() // <- I don't have this 
    }
```
The [doc on withJava()](https://kotlinlang.org/docs/multiplatform-dsl-reference.html#jvm-targets) says: 

> Use this function for projects that contain both Java and Kotlin source files.  

I didn't added because I don't have java source.

But it works now, i think I must have touched god. Thanks @breandan , you saved me!
